# Matplotlib

## Numpy

El paquete NumPy proporciona el objeto "ndarray". un ndarray de NumPy se usa para contener datos de tipo uniforme con un número arbitrario de dimensiones. NumPy proporciona métodos matemáticos y de matriz básicos. Aunque no necesitas entender a la perfección Numpy, si necesitas conocer las operaciones básicas que este proporciona. La siguiente instrucción de importación es la convención generalmente aceptada para NumPy.

In [1]:
import numpy as np

### Creación de los arrays
Hay varias formas de hacer matrices NumPy. Una matriz tiene tres atributos particulares que se pueden consultar: forma, tamaño y número de dimensiones.

In [2]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)

(3,)
3
1


In [3]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)

(100,)
100
1


In [4]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)

(5, 80)
400
2


In [7]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
# Scalar Indexing
print(x[2])

2


In [6]:
# Slicing
print(x[2:5])

[2 3 4]


In [8]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [0 1 2 3 4]
Row 18 to the end
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41
 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65
 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
 90 91 92 93 94 95 96 97 98 99]
Last 5 rows
 [95 96 97 98 99]
Reverse the rows
 [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]


In [9]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
